version: '3.8'

networks:
  mysqlnet:
    driver: bridge

services:

  mysql56:
    image: mysql:5.6
    container_name: ${APP_NAME:?err}-mysql56
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    volumes:
      - ./conf/mysql56_my.cnf:/etc/my.cnf
      - ./data/mysql56:/var/lib/mysql
      - ./logs/mysql56:/var/log/mysql
    networks:
      - mysqlnet

  mysql57:
    image: mysql:5.7
    container_name: ${APP_NAME:?err}-mysql57
    restart: unless-stopped
    tty: true
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    volumes:
      - ./conf/mysql57_my.cnf:/etc/my.cnf
      - ./data/mysql57:/var/lib/mysql
      - ./logs/mysql57:/var/log/mysql
    networks:
      - mysqlnet

  mysql80:
    image: mysql:8
    container_name: ${APP_NAME:?err}-mysql80
    restart: unless-stopped
    tty: true
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    volumes:
      - ./conf/mysql80_my.cnf:/etc/my.cnf
      - ./data/mysql80:/var/lib/mysql
      - ./logs/mysql80:/var/log/mysql
    networks:
      - mysqlnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME:?err}-phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    networks:
      - mysqlnet
    links:
      - 'mysql56:mysql56'
      - 'mysql57:mysql57'
      - 'mysql80:mysql80'
